services:
  db:
    image: postgres:16
    container_name: clinicflow_db
    environment:
      POSTGRES_DB: clinicflow
      POSTGRES_USER: clinicflow
      POSTGRES_PASSWORD: clinicflow123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: clinicflow_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
